import 'dart:io';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';

class PdfGenerator {
  static Future<File?> generateAnalysisReport(Map<String, dynamic> result, String patientName) async {
    final pdf = pw.Document();

    // Data extraction
    final stenosis = result['stenosis_percent'] ?? 0;
    final date = DateTime.now().toString().split(' ')[0];

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Padding(
            padding: const pw.EdgeInsets.all(30),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                // Header
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text('HeartCath AI Report', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.blue900)),
                    pw.Text('Date: $date', style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700)),
                  ],
                ),
                pw.Divider(thickness: 2, color: PdfColors.blue900),
                pw.SizedBox(height: 20),

                // Patient Info
                pw.Container(
                  padding: const pw.EdgeInsets.all(10),
                  decoration: pw.BoxDecoration(
                    color: PdfColors.grey100,
                    borderRadius: const pw.BorderRadius.all(pw.Radius.circular(5)),
                  ),
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('PATIENT INFORMATION', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
                      pw.SizedBox(height: 5),
                      pw.Text('Name: $patientName'),
                    ],
                  ),
                ),
                pw.SizedBox(height: 30),

                // Analysis Results
                pw.Text('ANALYSIS SUMMARY', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 10),
                pw.Text('The AI-powered analysis has detected the following stenosis levels in the coronary artery scans:'),
                pw.SizedBox(height: 20),

                // Visual Chart (Simplified Bar)
                pw.Row(
                  children: [
                    pw.Text('Stenosis Percentage:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                    pw.SizedBox(width: 10),
                    pw.Text('$stenosis%', style: pw.TextStyle(fontSize: 18, color: stenosis > 70 ? PdfColors.red : PdfColors.green)),
                  ],
                ),
                pw.SizedBox(height: 10),
                
                // Visualization Bar
                pw.Stack(
                  children: [
                    pw.Container(
                      height: 20,
                      width: double.infinity,
                      decoration: const pw.BoxDecoration(color: PdfColors.grey300),
                    ),
                    pw.Container(
                      height: 20,
                      width: (stenosis / 100) * 450, // Approx width ratio
                      decoration: pw.BoxDecoration(
                        color: stenosis > 70 ? PdfColors.red : (stenosis > 40 ? PdfColors.orange : PdfColors.green),
                      ),
                    ),
                  ],
                ),
                pw.SizedBox(height: 40),

                // Clinical Notes
                pw.Text('CLINICAL RECOMMENDATIONS', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 5),
                pw.Text(stenosis > 70 
                  ? 'Urgent clinical intervention recommended. Significant obstruction detected.'
                  : (stenosis > 40 ? 'Moderate stenosis. Routine follow-up and monitoring advised.' : 'Normal findings. No significant stenosis detected.')),

                pw.Spacer(),
                pw.Divider(),
                pw.Center(
                  child: pw.Text('Generated by HeartCath AI Clinical System', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey500)),
                ),
              ],
            ),
          );
        },
      ),
    );

    // Save the file
    final directory = await getApplicationDocumentsDirectory();
    final file = File('${directory.path}/heart_cath_report_${DateTime.now().millisecondsSinceEpoch}.pdf');
    await file.writeAsBytes(await pdf.save());
    
    return file;
  }
}
