// cspell:disable
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../app_state.dart';

class AppLocalizations {
  final String locale;

  AppLocalizations(this.locale);

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'settings': 'Settings',
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'arabic': 'Arabic',
      'english': 'English',
      'notifications': 'Notifications',
      'support': 'Support',
      'logout': 'Logout',
      'profile': 'Profile',
      'security': 'Security',
      'preferences': 'Preferences',
      'biometric_setting': 'Biometric Login',
      'new_analysis': 'New Analysis',
      'system_alerts': 'System Alerts',
      'help_center': 'Help Center',
      'home': 'Home',
      'history': 'History',
      'welcome': 'Hello, Dr. ',
      'ready_analysis': 'Ready for analysis today?',
      'patients': 'Patients',
      'reports': 'Reports',
      'add_patient': 'Add Patient',
      'manage_patients': 'Manage Patients',
      'analyze': 'Analyze',
      'upload_video': 'Upload Video',
      'dicom_converter': 'DICOM Converter',
      'insights': 'Clinical Insights',
      'pro_tip': 'Pro Tip',
      'pro_tip_desc': 'Upload DICOM files directly for better AI accuracy.',
      'analysisTitle': 'Analysis Result',
      'search_hint': 'Search by Name or ID',
      'patient_info': 'Patient Information',
      'medical_info': 'Medical Information',
      'name': 'Full Name',
      'age': 'Age',
      'phone': 'Phone Number',
      'gender': 'Gender',
      'chronic_diseases': 'Chronic Diseases',
      'doctor_notes': 'Doctor Notes',
      'save_patient': 'Save Patient',
      'no_patients_found': 'No patients found',
      'case_details': 'Case Details',
      'patient_name': 'Patient Name',
      'case_id': 'Case ID',
      'diagnosis': 'Diagnosis & Details',
      'stenosis': 'Stenosis level',
      'artery': 'Detected Artery',
      'download_report': 'Download Clinical Report',
      'email': 'Email Address',
      'extension': 'Extension',
      'edit_profile': 'Edit Profile',
      'save_changes': 'Save Changes',
      'change_password': 'Change Password',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'confirm_password': 'Confirm New Password',
      'update_email': 'Update Email',
      'new_email': 'New Email Address',
      'send_code': 'Send Verification Code',
      'email_verify_desc': 'A verification code will be sent to your new email address.',
      'welcome_back': 'Welcome Back',
      'sign_in_dash': 'Sign in to medical dashboard',
      'analysis_failed': 'Analysis Failed',
      'error_occurred': 'An error occurred during processing',
      'processing_desc': 'Analyzing angiography video...',
      'go_back': 'Go Back',
      'password_changed': 'Password changed successfully',
      'profile_updated': 'Profile updated successfully',
      'code_sent': 'Verification code sent',
      'select_patient': 'Select Patient',
      'password': 'Password',
      'password_hint': 'Enter your secure password',
      'email_hint': 'Enter your medical email',
      'forgot_password': 'Forgot Password?',
      'login': 'Login',
      'biometric_login': 'Or continue with biometrics',
      'dont_have_account': "Don't have an account? ",
      'sign_up': 'Sign Up',
      'dicom_desc': 'Convert medical scans to MP4 videos instantly.',
      'find_patient': 'Find Patient',
      'total_records': 'Total Records',
      'analyses_done': 'Analyses Done',
      'conversion_success': 'Conversion Success!',
      'convert_another': 'Convert Another',
      'share': 'Share Video',
      'invalid_credentials': 'Invalid email or password',
      'login_error': 'An error occurred during login',
      'connection_error': 'Connection lost. Please check your internet.',
      'server_error': 'Server error. Please try again later.',
      'unauthorized_error': 'Session expired. Please login again.',
      'forbidden_error': 'You do not have permission for this action.',
      'unknown_error': 'Something went wrong. Please try again.',
      'delete_patient_success': 'Patient deleted successfully',
    },
    'ar': {
      'settings': 'الإعدادات',
      'dark_mode': 'الوضع الليلي',
      'language': 'اللغة',
      'arabic': 'العربية',
      'english': 'الإنجليزية',
      'notifications': 'التنبيهات',
      'support': 'الدعم',
      'logout': 'تسجيل الخروج',
      'profile': 'الملف الشخصي',
      'security': 'الأمان',
      'preferences': 'التفضيلات',
      'biometric_setting': 'الدخول بالبصمة',
      'new_analysis': 'تحليل جديد',
      'system_alerts': 'تنبيهات النظام',
      'help_center': 'مركز المساعدة',
      'home': 'الرئيسية',
      'history': 'السجل',
      'welcome': 'مرحباً، د. ',
      'ready_analysis': 'هل أنت مستعد للتحليل اليوم؟',
      'patients': 'المرضى',
      'reports': 'التقارير',
      'add_patient': 'إضافة مريض',
      'manage_patients': 'إدارة المرضى',
      'analyze': 'تحليل',
      'upload_video': 'رفع فيديو',
      'dicom_converter': 'محول DICOM',
      'insights': 'رؤى سريرية',
      'pro_tip': 'نصيحة',
      'pro_tip_desc': 'ارفع ملفات DICOM مباشرة لدقة تحليل أعلى.',
      'analysisTitle': 'نتيجة التحليل',
      'search_hint': 'البحث بالاسم أو الرقم',
      'patient_info': 'معلومات المريض',
      'medical_info': 'المعلومات الطبية',
      'name': 'الاسم الكامل',
      'age': 'العمر',
      'phone': 'رقم الهاتف',
      'gender': 'الجنس',
      'chronic_diseases': 'الأمراض المزمنة',
      'doctor_notes': 'ملاحظات الطبيب',
      'save_patient': 'حفظ المريض',
      'no_patients_found': 'لم يتم العثور على مرضى',
      'case_details': 'تفاصيل الحالة',
      'patient_name': 'اسم المريض',
      'case_id': 'رقم الحالة',
      'diagnosis': 'التشخيص والتفاصيل',
      'stenosis': 'مستوى الضيق',
      'artery': 'الشريان المكتشف',
      'download_report': 'تحميل التقرير السريري',
      'email': 'البريد الإلكتروني',
      'extension': 'الرقم الداخلي',
      'edit_profile': 'تعديل الملف الشخصي',
      'save_changes': 'حفظ التغييرات',
      'change_password': 'تغيير كلمة المرور',
      'current_password': 'كلمة المرور الحالية',
      'new_password': 'كلمة المرور الجديدة',
      'confirm_password': 'تأكيد كلمة المرور',
      'update_email': 'تحديث البريد الإلكتروني',
      'new_email': 'البريد الإلكتروني الجديد',
      'send_code': 'إرسال رمز التحقق',
      'email_verify_desc': 'سيتم إرسال رمز التحقق إلى بريدك الإلكتروني الجديد.',
      'welcome_back': 'مرحباً بعودتك',
      'sign_in_dash': 'سجل الدخول لوحة التحكم الطبية',
      'analysis_failed': 'فشل التحليل',
      'error_occurred': 'حدث خطأ أثناء المعالجة',
      'processing_desc': 'جاري تحليل فيديو تصوير الشرايين...',
      'go_back': 'العودة',
      'password_changed': 'تم تغيير كلمة المرور بنجاح',
      'profile_updated': 'تم تحديث الملف الشخصي بنجاح',
      'code_sent': 'تم إرسال رمز التحقق',
      'select_patient': 'اختر المريض',
      'password': 'كلمة المرور',
      'password_hint': 'أدخل كلمة المرور الخاصة بك',
      'email_hint': 'أدخل بريدك الإلكتروني الطبي',
      'forgot_password': 'نسيت كلمة المرور؟',
      'login': 'تسجيل الدخول',
      'biometric_login': 'أو المتابعة باستخدام البصمة',
      'dont_have_account': 'ليس لديك حساب؟ ',
      'sign_up': 'إنشاء حساب',
      'dicom_desc': 'حول صور الأشعة إلى فيديوهات MP4 فوراً.',
      'find_patient': 'البحث عن مريض',
      'total_records': 'إجمالي السجلات',
      'analyses_done': 'التحليلات المكتملة',
      'conversion_success': 'تم التحويل بنجاح!',
      'convert_another': 'تحويل ملف آخر',
      'share': 'مشاركة الفيديو',
      'invalid_credentials': 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
      'login_error': 'حدث خطأ أثناء تسجيل الدخول',
      'connection_error': 'انقطع الاتصال. يرجى التحقق من الإنترنت.',
      'server_error': 'خطأ في السيرفر. يرجى المحاولة لاحقاً.',
      'unauthorized_error': 'انتهت الجلسة. يرجى تسجيل الدخول مرة أخرى.',
      'forbidden_error': 'ليس لديك صلاحية للقيام بهذا الإجراء.',
      'unknown_error': 'حدث خطأ ما. يرجى المحاولة مرة أخرى.',
      'delete_patient_success': 'تم مسح المريض بنجاح',
    },
  };

  String translate(String key) {
    return _localizedValues[locale]?[key] ?? key;
  }
}

extension TranslateExtension on String {
  String tr(BuildContext context, {bool listen = true}) {
    final appState = Provider.of<AppState>(context, listen: listen);
    return AppLocalizations(appState.locale).translate(this);
  }
}
